version: '3'
services:
    app:
        image: schemato/testapp:latest
        env_file:
            - secrets.env
        ports:
            - 127.0.0.1:3000:3000
        depends_on:
            - pg
    pg:
        image: postgres:11.5-alpine
